//! Structural validation of the OmniBridge brand artwork.
//!
//! The marks are source-controlled vectors that get compiled into the binary
//! and shipped as the application icon, so what can go wrong with them is not
//! "it looks off" — it is that an asset quietly starts depending on something
//! that will not be there:
//!
//! * an embedded raster, which stops it being a vector at all;
//! * a network reference, which a desktop icon must never make;
//! * a bundled or named font, which a person's machine may not have and which
//!   the typography decision forbids shipping;
//! * a filesystem path left behind by an editor, which leaks whose machine it
//!   was drawn on;
//! * a stroke so fine that the mark disappears at 16 px, which is the one
//!   size an application icon is guaranteed to be drawn at.
//!
//! None of that is visible by looking at the picture, which is why it is
//! checked here. How the marks *look* at each size is a human judgement and
//! is recorded in the sprint report instead.
//!
//! This is a GUI-crate test target on purpose. It reads desktop artwork and
//! is not part of the portable core, so it is outside the boundary
//! `portable-windows-msvc.yml` measures — that job's classification guards
//! watch `core/tests` and `capabilities/notifications/tests`, and neither is
//! this.

use std::path::{Path, PathBuf};

/// The canonical asset directory, relative to this crate.
fn assets() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/design/assets")
}

/// The OmniBridge artwork this application shipped until rebrand Wave 7.
///
/// Named one by one rather than globbed: a new asset should have to state that
/// it exists, and an asset that is deleted should fail here rather than stop
/// being checked silently.
///
/// Nothing compiles or installs these any more: since Wave 7 the desktop draws
/// the Pliwee masters and `pliwee-app-icon.svg` (the tests at the end of this
/// file). They stay in the tree, and stay checked, until they are retired.
/// All six are the approved OmniBridge artwork, as it was installed verbatim. None is
/// redrawn, retraced or regenerated by this repository, which is why the tests
/// below check *relationships between* them rather than second-guessing their
/// shapes.
const ASSETS: [&str; 6] = [
    "omnibridge-mark.svg",
    "omnibridge-mark-mono.svg",
    "omnibridge-app-icon.svg",
    "omnibridge-android-monochrome.svg",
    "omnibridge-wordmark.svg",
    "omnibridge-logo-lockup.svg",
];

/// The assets that are not the canonical mark but must be built out of it.
///
/// The wordmark is excluded on purpose: it is letterforms, not the symbol, and
/// carries none of the mark's geometry.
const DERIVED_FROM_THE_MARK: [&str; 4] = [
    "omnibridge-mark-mono.svg",
    "omnibridge-app-icon.svg",
    "omnibridge-android-monochrome.svg",
    "omnibridge-logo-lockup.svg",
];

fn read(name: &str) -> String {
    let path = assets().join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{} is missing: {e}", path.display()))
}

/// Pulls an attribute off the first element that carries it.
///
/// Matched on a whole attribute name, not a substring: `d="` also occurs
/// inside `id="`, and a scanner that does not care about the boundary reads a
/// gradient's name as a path's geometry.
fn attr(svg: &str, name: &str) -> Option<String> {
    let needle = format!("{name}=\"");
    svg.match_indices(&needle)
        .find(|(index, _)| {
            *index == 0
                || svg[..*index]
                    .chars()
                    .next_back()
                    .is_some_and(|c| c.is_whitespace() || c == '<')
        })
        .and_then(|(index, _)| svg[index + needle.len()..].split('"').next())
        .map(str::to_string)
}

/// The canonical symbol's outline, read out of the canonical file.
///
/// This one string is what every other asset has to agree with, and it is
/// taken from the artwork rather than written down here — a constant copied
/// into this file would only prove that the constant matches itself.
fn canonical_silhouette() -> String {
    const OPEN: &str = "<clipPath id=\"clip\"><path d=\"";
    let svg = read("omnibridge-mark.svg");
    let at = svg
        .find(OPEN)
        .expect("the canonical mark defines its outline as a clip path");
    svg[at + OPEN.len()..]
        .split('"')
        .next()
        .expect("the outline is a quoted attribute")
        .to_string()
}

#[test]
fn every_asset_is_a_self_contained_svg() {
    for name in ASSETS {
        let svg = read(name);
        assert!(
            svg.contains("<svg") && svg.trim_end().ends_with("</svg>"),
            "{name} is not an SVG document"
        );
        assert!(
            svg.contains("xmlns=\"http://www.w3.org/2000/svg\""),
            "{name} does not declare the SVG namespace"
        );
        // Without a viewBox the mark does not scale, which is the entire
        // reason it is a vector.
        assert!(attr(&svg, "viewBox").is_some(), "{name} has no viewBox");
        assert_eq!(
            svg.matches("<svg").count(),
            1,
            "{name} has more than one root"
        );
    }
}

/// Nothing is fetched, embedded or inherited from outside the file.
///
/// `<use href="#…">` is *not* forbidden, and that is the one interesting line
/// here. The approved artwork composes itself out of a `<symbol>` it defines
/// a few lines earlier, which is a same-document reference and stays valid
/// wherever the file is opened. What must never appear is a reference that
/// leaves the document.
#[test]
fn no_asset_reaches_outside_itself() {
    for name in ASSETS {
        let svg = read(name);
        let lower = svg.to_lowercase();

        for forbidden in [
            "<image",     // an embedded or linked raster
            "data:image", // a raster smuggled in as a data URI
            "<script",    // an icon is not a program
            "@font-face", // a bundled font
            "<font",
            ".ttf",
            ".woff",
            "<text", // text in a mark is a font dependency by another name
            "font-family",
        ] {
            assert!(
                !lower.contains(forbidden),
                "{name} contains {forbidden:?}, which makes it depend on something outside itself"
            );
        }

        // Every reference stays inside this document.
        for (index, _) in lower.match_indices("href=\"") {
            let target: String = lower[index + 6..]
                .chars()
                .take_while(|c| *c != '"')
                .collect();
            assert!(
                target.starts_with('#'),
                "{name} references {target:?}, which is outside the file"
            );
        }

        // The namespace declaration is a URI, not a fetch. Any *other* http
        // reference would be.
        let http_uses: Vec<&str> = lower
            .match_indices("http")
            .map(|(i, _)| &lower[i..(i + 40).min(lower.len())])
            .filter(|s| !s.starts_with("http://www.w3.org/2000/svg"))
            .collect();
        assert!(
            http_uses.is_empty(),
            "{name} references the network: {http_uses:?}"
        );

        // An editor that wrote out where it was run leaks the author's
        // machine into a file that ships.
        for leak in [
            "/home/",
            "/users/",
            "file://",
            "c:\\",
            "sodipodi",
            "inkscape:",
        ] {
            assert!(
                !lower.contains(leak),
                "{name} leaks a local path or editor state: {leak:?}"
            );
        }
    }
}

/// Every gradient a mark paints with is defined in that same mark.
///
/// A `url(#id)` that resolves to nothing does not fail loudly — the shape is
/// simply painted black, or not at all, which is exactly the kind of breakage
/// that reaches a release.
#[test]
fn every_paint_reference_resolves_inside_its_own_file() {
    for name in ASSETS {
        let svg = read(name);
        for (index, _) in svg.match_indices("url(#") {
            let id: String = svg[index + 5..].chars().take_while(|c| *c != ')').collect();
            assert!(
                svg.contains(&format!("id=\"{id}\"")),
                "{name} paints with url(#{id}), which it never defines"
            );
        }
    }
}

/// An id is unique within the file that defines it.
///
/// Scoped per file, not across the family, and the difference is the point.
/// The approved assets all define `base`, `front`, `shadow` and `clip`,
/// because each is a standalone document carrying its own copy of the artwork
/// — that is what makes them independently openable. A collision only matters
/// *inside* one document, where the second definition silently wins.
#[test]
fn gradient_ids_are_unique_within_each_file() {
    for name in ASSETS {
        let svg = read(name);
        let mut seen: Vec<String> = Vec::new();
        for (index, _) in svg.match_indices("id=\"") {
            let id: String = svg[index + 4..].chars().take_while(|c| *c != '"').collect();
            assert!(!seen.contains(&id), "{name} defines id {id:?} twice");
            seen.push(id);
        }
    }
}

/// Every derived asset carries the canonical outline, byte for byte.
///
/// This is the assertion the whole sprint rests on, and it is deliberately
/// made on geometry rather than on filenames: a file called
/// `omnibridge-app-icon.svg` that drew something else would pass a name check
/// and fail this one. The outline is thousands of characters of coordinates,
/// so an equality here is not a coincidence — it is the same artwork.
#[test]
fn every_derived_asset_carries_the_canonical_geometry() {
    let canonical = canonical_silhouette();
    assert!(
        canonical.len() > 2000,
        "the canonical outline is implausibly short ({} chars), so this test is \
         not proving what it claims",
        canonical.len()
    );
    for name in DERIVED_FROM_THE_MARK {
        let svg = read(name);
        assert!(
            svg.contains(&canonical),
            "{name} does not carry the canonical outline from omnibridge-mark.svg"
        );
    }
}

/// The monochrome cuts must actually be monochrome, and must take their colour
/// from wherever they are placed rather than hard-coding one.
#[test]
fn the_monochrome_cuts_inherit_their_colour() {
    for name in [
        "omnibridge-mark-mono.svg",
        "omnibridge-android-monochrome.svg",
    ] {
        let svg = read(name);
        assert!(
            svg.contains("fill=\"currentColor\""),
            "{name} must inherit the text colour, so it works on light and dark alike"
        );
        // The colour cut's symbol is defined in these files too — an
        // unreferenced leftover of the shared source — so what matters is that
        // nothing the mono cut actually *draws* reaches for it.
        let drawn = svg
            .rsplit_once("</defs>")
            .expect("the drawable content follows the defs")
            .1;
        assert!(
            !drawn.contains("url(#"),
            "{name} paints its visible content with a gradient: {drawn}"
        );
    }
}

/// The application icon places the canonical mark on the 512-unit grid every
/// platform icon pipeline expects.
#[test]
fn the_app_icon_is_the_canonical_mark_on_an_icon_grid() {
    let svg = read("omnibridge-app-icon.svg");
    assert_eq!(
        attr(&svg, "viewBox").as_deref(),
        Some("0 0 512 512"),
        "an application icon is square and 512 units on a side"
    );
    assert!(
        svg.contains("href=\"#mark\""),
        "the app icon must place the mark symbol rather than an inlined copy of it"
    );
    assert!(
        svg.contains(&canonical_silhouette()),
        "the app icon does not carry the canonical outline"
    );
}

/// No active artwork still carries the pre-rename identity.
///
/// Byte-level and case-insensitive, because what is being guarded against is a
/// `<title>`, an `aria-label` or a gradient id left behind by a copy — none of
/// which changes how the file looks, and all of which make the shipped artwork
/// claim to be AnyFlow.
#[test]
fn no_active_asset_carries_the_pre_rename_identity() {
    for name in ASSETS {
        let lower = read(name).to_lowercase();
        for dead in [
            "anyflow", "flow a", "flow-a", "flow_a", "one flow", "fedroid",
        ] {
            assert!(
                !lower.contains(dead),
                "{name} still carries the pre-rename identity {dead:?}"
            );
        }
    }
}

// ===========================================================================
// PLIWEE-W0 — the Pliwee vector masters (ADR-0020 D8)
// ===========================================================================
//
// The Pliwee masters sit beside the OmniBridge artwork above and do not
// replace it yet: nothing is compiled from them until the platform waves (W6,
// W7) derive their icons, so `ASSETS` — the artwork the application ships —
// is left exactly as it was, dead list included.
//
// The masters are a controlled vector reconstruction of the owner-supplied
// board (`docs/design/references/`). They are BRAND APPROVED (final human
// brand approval, 2026-09-24, commit 1ea65e6): canonical and frozen, and
// every future derivative starts from them. These tests do not approve
// anything. They pin what a machine can pin: that the files are
// self-contained vectors, that the approved geometry has not moved, that
// every cut and the lockup carry it byte for byte, that the mono cut is one
// ink, and that the lettering is outlines rather than a font request.

/// The Pliwee masters, named one by one for the same reason `ASSETS` is.
const PLIWEE_MASTERS: [&str; 5] = [
    "pliwee-mark.svg",
    "pliwee-mark-mono.svg",
    "pliwee-mark-tonal.svg",
    "pliwee-wordmark.svg",
    "pliwee-lockup.svg",
];

/// FNV-1a (64-bit) of the approved Flow Monogram geometry: every
/// `id "\n" d "\n"` of `pliwee-mark.svg`'s four face paths, in order.
///
/// Pinned deliberately. The geometry was approved by the owner on 2026-09-24
/// (Wave 0 review 2, commit c6fbe99's paths) and must not move: a retrace, a
/// re-export or a "cleanup" that shifts one coordinate fails here. Changing
/// this constant is an owner brand decision, never a fix for a red test.
const APPROVED_MARK_GEOMETRY_FNV1A64: u64 = 0xd691_83f7_9880_0e87;

fn fnv1a64(bytes: impl IntoIterator<Item = u8>) -> u64 {
    bytes.into_iter().fold(0xcbf2_9ce4_8422_2325, |h, b| {
        (h ^ u64::from(b)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}

/// Every `<path id="…" d="…"/>` a Pliwee master defines, as (id, d).
///
/// The Pliwee masters define each ribbon face once, by id, and paint it by
/// reference — so this list *is* the mark's geometry.
fn pliwee_geometry(svg: &str) -> Vec<(String, String)> {
    svg.match_indices("<path id=\"")
        .map(|(at, open)| {
            let rest = &svg[at + open.len()..];
            let id = rest.split('"').next().expect("an id").to_string();
            let d = attr(rest, "d").unwrap_or_else(|| panic!("path {id} has no d"));
            (id, d)
        })
        .collect()
}

/// The Pliwee masters pass every structural check the shipped artwork passes.
///
/// The checks are the ones above, reused rather than restated, so a master
/// cannot be held to a weaker standard than the artwork it will replace.
#[test]
fn every_pliwee_master_is_a_self_contained_vector() {
    for name in PLIWEE_MASTERS {
        let svg = read(name);
        let lower = svg.to_lowercase();
        assert!(
            svg.contains("xmlns=\"http://www.w3.org/2000/svg\"")
                && svg.trim_end().ends_with("</svg>"),
            "{name} is not an SVG document"
        );
        assert_eq!(
            svg.matches("<svg").count(),
            1,
            "{name} has more than one root"
        );
        assert!(attr(&svg, "viewBox").is_some(), "{name} has no viewBox");
        for forbidden in [
            "<image",
            "data:",
            "<script",
            "@font-face",
            "<font",
            ".ttf",
            ".woff",
            "<text",
            "font-family",
            "<filter",
            "<foreignobject",
        ] {
            assert!(
                !lower.contains(forbidden),
                "{name} contains {forbidden:?}; a master is plain vector geometry and paint"
            );
        }
        for (index, _) in lower.match_indices("href=\"") {
            assert!(
                lower[index + 6..].starts_with('#'),
                "{name} references something outside the file"
            );
        }
        let http: Vec<&str> = lower
            .match_indices("http")
            .map(|(i, _)| &lower[i..(i + 40).min(lower.len())])
            .filter(|s| !s.starts_with("http://www.w3.org/2000/svg"))
            .collect();
        assert!(http.is_empty(), "{name} references the network: {http:?}");
        for leak in [
            "/home/",
            "/users/",
            "file://",
            "c:\\",
            "sodipodi",
            "inkscape:",
        ] {
            assert!(!lower.contains(leak), "{name} leaks {leak:?}");
        }
        for (index, _) in svg.match_indices("url(#") {
            let id: String = svg[index + 5..].chars().take_while(|c| *c != ')').collect();
            assert!(
                svg.contains(&format!("id=\"{id}\"")),
                "{name} paints with url(#{id}), which it never defines"
            );
        }
        let mut seen: Vec<String> = Vec::new();
        for (index, _) in svg.match_indices(" id=\"") {
            let id: String = svg[index + 5..].chars().take_while(|c| *c != '"').collect();
            assert!(!seen.contains(&id), "{name} defines id {id:?} twice");
            seen.push(id);
        }
    }
}

/// The Flow Monogram's geometry is the approved geometry, to the byte.
#[test]
fn the_pliwee_mark_geometry_is_the_approved_geometry() {
    let colour = pliwee_geometry(&read("pliwee-mark.svg"));
    let ids: Vec<&str> = colour.iter().map(|(id, _)| id.as_str()).collect();
    assert_eq!(
        ids,
        ["silhouette", "face-loop", "face-tail", "face-sweep"],
        "the colour mark no longer defines the four Flow Monogram faces"
    );
    let total: usize = colour.iter().map(|(_, d)| d.len()).sum();
    assert!(
        total > 20_000,
        "the mark's geometry is implausibly short ({total} chars), so equality proves nothing"
    );
    let digest = fnv1a64(
        colour
            .iter()
            .flat_map(|(id, d)| [id.as_bytes(), b"\n", d.as_bytes(), b"\n"])
            .flatten()
            .copied(),
    );
    assert_eq!(
        digest, APPROVED_MARK_GEOMETRY_FNV1A64,
        "pliwee-mark.svg's geometry is not the owner-approved Flow Monogram \
         (digest {digest:#018x}); the geometry changes only by brand decision"
    );
}

/// The mono and tonal cuts are the colour mark's geometry with other paint.
///
/// Not "similar": the same face paths, same ids, same bytes. A cut may only
/// change how that geometry is painted.
#[test]
fn the_pliwee_mono_and_tonal_cuts_repaint_the_colour_geometry() {
    let colour = pliwee_geometry(&read("pliwee-mark.svg"));
    for name in ["pliwee-mark-mono.svg", "pliwee-mark-tonal.svg"] {
        assert_eq!(
            colour,
            pliwee_geometry(&read(name)),
            "{name} does not carry the colour mark's geometry"
        );
    }
}

/// The mono cut is one ink: `currentColor`, and nothing that could make two
/// parts of the mark differ — no tone, no opacity, no mask, no gradient.
///
/// Tonal separation is what `pliwee-mark-tonal.svg` is for; the mono master
/// must stay usable wherever exactly one colour is allowed.
#[test]
fn the_pliwee_mono_mark_is_a_single_ink() {
    let svg = read("pliwee-mark-mono.svg");
    let drawn = svg
        .split("<symbol id=\"markMono\"")
        .nth(1)
        .and_then(|s| s.split("</symbol>").next())
        .expect("the mono cut defines a markMono symbol");
    let fills: Vec<&str> = drawn
        .match_indices("fill=\"")
        .map(|(at, open)| drawn[at + open.len()..].split('"').next().unwrap_or(""))
        .collect();
    assert!(
        !fills.is_empty() && fills.iter().all(|f| *f == "currentColor"),
        "the mono cut paints with {fills:?}; it must paint with currentColor only"
    );
    for forbidden in ["opacity", "mask", "url(#", "stroke"] {
        assert!(
            !drawn.contains(forbidden),
            "the mono cut uses {forbidden:?}, which is not a single ink"
        );
    }
    for forbidden in ["<linearGradient", "<radialGradient", "<mask"] {
        assert!(
            !svg.contains(forbidden),
            "the mono file carries {forbidden:?}; a single-ink master has no second paint"
        );
    }
    assert!(
        svg.contains("<use href=\"#markMono\""),
        "the mono file does not draw the mono cut"
    );

    // The tonal cut is the optional one-colour-with-tones variant.
    let tonal = read("pliwee-mark-tonal.svg");
    assert!(
        tonal.contains("<use href=\"#markTonal\"") && tonal.contains("fill=\"currentColor\""),
        "the tonal file does not draw a currentColor tonal cut"
    );
    assert!(
        !tonal.contains("url(#paint"),
        "the tonal cut paints with a gradient"
    );
}

/// The lockup places the same mark; it does not carry a second drawing of it.
#[test]
fn the_pliwee_lockup_carries_the_mark_geometry() {
    let mark = pliwee_geometry(&read("pliwee-mark.svg"));
    let lockup = read("pliwee-lockup.svg");
    for (id, d) in &mark {
        assert!(
            lockup.contains(&format!("<path id=\"{id}\" d=\"{d}\"")),
            "the lockup's {id} is not the mark's"
        );
    }
    assert!(
        lockup.contains("href=\"#mark\""),
        "the lockup does not place the mark symbol"
    );
}

/// The wordmark and the lockup's lettering are outlines.
///
/// "Pliwee" is custom brand lettering traced from the board, not set from a
/// font. `<text>` and `font-family` are already refused above; this asserts
/// the positive half — there is lettering, drawn as paths — and that the
/// wordmark and the lockup carry the same outlines.
#[test]
fn the_pliwee_wordmark_is_outlined_and_shared_with_the_lockup() {
    let wordmark = read("pliwee-wordmark.svg");
    let lockup = read("pliwee-lockup.svg");
    let glyphs: Vec<String> = wordmark
        .match_indices("<path ")
        .filter_map(|(at, _)| attr(&wordmark[at..], "d"))
        .collect();
    assert_eq!(
        glyphs.len(),
        6,
        "the wordmark is six outlined letters: P l i w e e"
    );
    let word_group = |svg: &str| -> String {
        svg.split("<g id=\"wordmark\"")
            .nth(1)
            .and_then(|s| s.split("</g>").next())
            .expect("a wordmark group")
            .split_once('>')
            .expect("the group opens")
            .1
            .to_string()
    };
    assert_eq!(
        word_group(&wordmark),
        word_group(&lockup),
        "the lockup sets Pliwee with different outlines than the wordmark"
    );
}

/// The lettering is painted with its board-derived inks, not with UI tokens.
///
/// Like the Flow Monogram's gradient stops, these are brand-asset colours
/// measured on the canonical board and approved by the owner: the Pliwee
/// Wordmark Ink `#030D25` and the lockup tagline `#314871`. The UI's Dark
/// token (`#0B1020`) is a different colour for a different job, and a
/// derivative that "tidies" the wordmark onto it changes the approved logo.
#[test]
fn the_pliwee_lettering_uses_its_board_derived_inks() {
    let fill_of = |svg: &str, group: &str| -> String {
        let open = format!("<g id=\"{group}\"");
        let at = svg
            .find(&open)
            .unwrap_or_else(|| panic!("no {group} group"));
        let tag = svg[at..].split('>').next().expect("the group opens");
        attr(tag, "fill").unwrap_or_else(|| panic!("the {group} group has no fill"))
    };
    for name in ["pliwee-wordmark.svg", "pliwee-lockup.svg"] {
        assert_eq!(
            fill_of(&read(name), "wordmark"),
            "#030D25",
            "{name} does not paint Pliwee with the Pliwee Wordmark Ink"
        );
    }
    assert_eq!(
        fill_of(&read("pliwee-lockup.svg"), "tagline"),
        "#314871",
        "the lockup's tagline is not the approved lockup tagline colour"
    );
}

/// No Pliwee master carries a retired identity — and the lockup carries the
/// adopted tagline.
///
/// This is the one place the dead list differs from `ASSETS`', and the
/// difference is ADR-0020 D8, not a relaxation: *One flow. Any device.* was
/// AnyFlow's tagline, is Pliwee's by decision, and so leaves this list;
/// `omnibridge` and `one bridge` join it. The AnyFlow fragments that were
/// never the tagline (`flow a`, `flow-a`, `flow_a`, `flowing`) stay dead, and
/// the masters' names and ids avoid them rather than removing them.
#[test]
fn no_pliwee_master_carries_a_retired_identity() {
    for name in PLIWEE_MASTERS {
        let lower = read(name).to_lowercase();
        for dead in [
            "anyflow",
            "flow a",
            "flow-a",
            "flow_a",
            "flowing",
            "fedroid",
            "omnibridge",
            "one bridge",
        ] {
            assert!(
                !lower.contains(dead),
                "{name} carries the retired identity {dead:?}"
            );
        }
    }
    // The re-adoption is asserted, not merely permitted: the lockup names the
    // tagline it draws, exactly as approved.
    let lockup = read("pliwee-lockup.svg");
    assert!(
        lockup.contains("aria-label=\"Pliwee — One flow. Any device.\""),
        "the lockup does not declare the approved tagline"
    );
}

// ===========================================================================
// BRAND-POLISH-01 — the application icon, as the desktop resolves it
// ===========================================================================
//
// Everything above asks whether the artwork is sound. These ask whether the
// desktop can *find* it, which is a different question and the one that was
// actually wrong: the marks were correct and compiled in, and GNOME Shell
// still drew a generic square, because on Wayland the shell resolves a
// window's icon entirely outside the application:
//
//     xdg_toplevel.set_app_id(APP_ID)   -> APP_ID.desktop from XDG_DATA_DIRS
//                                       -> its Icon= name
//                                       -> that name in the shell's theme
//
// Four names have to be the same string for that to land, and they live in
// four different files. That is what these pin.

/// This crate's data directory.
fn data() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("data")
}

/// The application id, read out of the source rather than restated here.
///
/// Restating it would make this file agree with itself while disagreeing with
/// the application, which is exactly the failure being guarded against.
fn app_id_from_source() -> String {
    let lib = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("src/lib.rs"))
        .expect("src/lib.rs is readable");
    let line = lib
        .lines()
        .find(|l| l.trim_start().starts_with("const APP_ID:"))
        .expect("src/lib.rs declares APP_ID");
    line.split('"')
        .nth(1)
        .expect("APP_ID is a string literal")
        .to_string()
}

/// One key from the `[Desktop Entry]` group.
///
/// Stops at the first group header so that `[Desktop Action quick-panel]`'s
/// own `Name` and `Exec` cannot be read as the entry's.
fn desktop_entry_key(key: &str) -> Option<String> {
    let text = std::fs::read_to_string(data().join(format!("{}.desktop", app_id_from_source())))
        .expect("the desktop entry is readable");
    let mut in_entry = false;
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_entry = line == "[Desktop Entry]";
            continue;
        }
        if !in_entry || line.starts_with('#') {
            continue;
        }
        if let Some(value) = line.strip_prefix(&format!("{key}=")) {
            return Some(value.to_string());
        }
    }
    None
}

/// A + C. The file's basename, the id in the source and the `Icon=` key are
/// one string.
///
/// A mismatch in any direction is the defect: the shell looks the window's
/// app_id up as a desktop-file id, then looks that file's `Icon=` up as an
/// icon name, and a miss at either step is a grey square with no error
/// anywhere.
#[test]
fn the_application_id_names_the_desktop_entry_and_its_icon() {
    let app_id = app_id_from_source();
    assert!(
        app_id.contains('.') && !app_id.contains('/') && !app_id.contains(' '),
        "{app_id} is not usable as a D-Bus name and a desktop file id"
    );

    let entry = data().join(format!("{app_id}.desktop"));
    assert!(
        entry.is_file(),
        "no desktop entry at {} — the shell matches a window by this filename",
        entry.display()
    );

    assert_eq!(
        desktop_entry_key("Icon").as_deref(),
        Some(app_id.as_str()),
        "Icon= must be the application id, or the shell searches for a name \
         nothing installs"
    );
}

/// B + I. The icon name the *application* asks for, the name the desktop
/// entry declares, and the filename the installer writes are the same.
///
/// The three places that name has to appear are in three languages — Rust,
/// an ini file and a shell script — so nothing but a test can keep them
/// together.
#[test]
fn every_layer_asks_for_the_same_icon_name() {
    let app_id = app_id_from_source();

    // The application: `install_icons` sets the default window icon name.
    let lib = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("src/lib.rs"))
        .expect("src/lib.rs is readable");
    assert!(
        lib.contains("set_default_icon_name(APP_ID)"),
        "the window icon name is no longer the application id"
    );

    // build.rs, which derives the compiled-in icon-theme copy.
    let build = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("build.rs"))
        .expect("build.rs is readable");
    assert!(
        build.contains(&format!("const APP_ID: &str = \"{app_id}\"")),
        "build.rs names a different application id than src/lib.rs"
    );

    // The installer, which is what a Wayland session actually reads.
    let installer = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tools/install-desktop-metadata.sh"),
    )
    .expect("the installer is readable");
    assert!(
        installer.contains(&format!("APP_ID=\"{app_id}\"")),
        "the installer names a different application id"
    );
    // And it installs the icon where an icon theme is looked up, under that
    // name. A scalable SVG needs no size directory of its own.
    assert!(
        installer.contains("share/icons/hicolor/scalable/apps"),
        "the installer does not write into a hicolor icon theme"
    );
    assert!(
        installer.contains("$APP_ID.svg"),
        "the installer does not name the icon after the application id"
    );
    // The same canonical file the brand documentation points at and build.rs
    // compiles in — not a second copy that could drift.
    assert!(
        installer.contains("docs/design/assets/pliwee-app-icon.svg"),
        "the installer does not install the canonical app icon"
    );
}

/// D. `Exec=` still names the binary this crate builds, and the Quick Panel
/// action still passes the flag the application parses.
#[test]
fn the_desktop_entry_launches_this_binary() {
    let exec = desktop_entry_key("Exec").expect("the entry has an Exec key");
    // The [[bin]] name in Cargo.toml, which is what a package puts on PATH.
    let manifest =
        std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml"))
            .expect("Cargo.toml is readable");
    assert!(
        manifest.contains("name = \"pliwee-gui\""),
        "the binary is no longer called pliwee-gui"
    );
    assert_eq!(exec, "pliwee-gui", "Exec= no longer names the binary");

    let text = std::fs::read_to_string(data().join(format!("{}.desktop", app_id_from_source())))
        .expect("the desktop entry is readable");
    // The launcher shortcut is a caller of the same activation seam as
    // `app.quick-panel`, and its flag has to be one the binary accepts.
    assert!(
        text.contains("Exec=pliwee-gui --quick-panel"),
        "the Quick Panel shortcut no longer passes --quick-panel"
    );
    let lib = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("src/lib.rs"))
        .expect("src/lib.rs is readable");
    assert!(
        lib.contains("\"--quick-panel\""),
        "the binary no longer parses the flag the desktop entry passes"
    );

    // D-Bus activation is the seam a shell uses to raise an already-running
    // OmniBridge rather than starting a second process, and it only works
    // because the bus name is the desktop file id.
    assert_eq!(
        desktop_entry_key("DBusActivatable").as_deref(),
        Some("true")
    );

    // The X11 association, which is a *different* string from the app id and
    // measured rather than assumed: GTK sets a Wayland app_id from the
    // GApplication id and an X11 WM_CLASS from the program name.
    assert_eq!(
        desktop_entry_key("StartupWMClass").as_deref(),
        Some("pliwee-gui"),
        "without this an X11 window matches no launcher"
    );
}

/// E. The icon is compiled into the binary at the path a `GtkIconTheme`
/// looks for, and the resource list and the deriving build step agree.
#[test]
fn the_icon_is_compiled_in_at_an_icon_theme_path() {
    let app_id = app_id_from_source();
    let gresource = std::fs::read_to_string(data().join("pliwee.gresource.xml"))
        .expect("the resource list is readable");
    let want = format!("icons/scalable/apps/{app_id}.svg");
    assert!(
        gresource.contains(&want),
        "the resource list does not carry {want}"
    );

    let build = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("build.rs"))
        .expect("build.rs is readable");
    assert!(
        build.contains("icons/scalable/apps"),
        "build.rs no longer derives the icon-theme copy"
    );
    assert!(
        build.contains("app-icon.svg"),
        "build.rs no longer derives it from the canonical app icon"
    );

    // And the prefix the application adds to the icon theme is the one the
    // resources are compiled under, or the lookup finds nothing.
    let lib = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("src/lib.rs"))
        .expect("src/lib.rs is readable");
    let prefix = format!("/{}/icons", app_id.replace('.', "/"));
    assert!(
        lib.contains(&format!("add_resource_path(\"{prefix}\"")),
        "the icon theme prefix is not {prefix}"
    );
}

/// K. The application icon the desktop resolves is the Pliwee app icon, whose
/// mark is established by geometry (see `the_desktop_app_icon_is_a_placement_of_the_pliwee_master`).
#[test]
fn the_primary_application_icon_is_the_canonical_mark() {
    // The icon build.rs publishes into the icon theme is the approved app icon,
    // and it carries the canonical outline.
    let build = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("build.rs"))
        .expect("build.rs is readable");
    assert!(
        build.contains("docs/design/assets/pliwee-app-icon.svg"),
        "build.rs does not derive the application icon from the Pliwee app icon"
    );
    assert_eq!(
        pliwee_geometry(&read("pliwee-app-icon.svg")),
        pliwee_geometry(&read("pliwee-mark.svg")),
        "the application icon does not carry the approved Pliwee geometry"
    );

    // Nothing anywhere in the icon path still names a retired mark.
    let gresource = std::fs::read_to_string(data().join("pliwee.gresource.xml"))
        .expect("the resource list is readable");
    let installer = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tools/install-desktop-metadata.sh"),
    )
    .expect("the installer is readable");
    for (where_, text) in [
        ("the resource list", &gresource),
        ("build.rs", &build),
        ("the installer", &installer),
    ] {
        // The OmniBridge artwork joins the list at Wave 7: the desktop no
        // longer compiles or installs any of it.
        for dead in [
            "flow-a",
            "flowing-ribbon",
            "ribbon-connection",
            "anyflow",
            "omnibridge-mark",
            "omnibridge-app-icon",
        ] {
            assert!(
                !text.contains(dead),
                "{where_} still names the retired mark {dead:?}"
            );
        }
    }

    // And there is exactly one application icon: a second one installed under
    // a name the shell might pick up is how two identities appear.
    assert!(
        installer.matches("share/icons/hicolor").count() >= 1,
        "the installer does not install an icon at all"
    );
}

/// The installer is a file a person runs and a package calls. Both need it to
/// be executable, to refuse a relative prefix, and never to need root.
#[test]
fn the_installer_is_safe_to_run_unprivileged() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tools/install-desktop-metadata.sh");
    let text = std::fs::read_to_string(&path).expect("the installer is readable");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&path).expect("stat").permissions().mode();
        assert!(
            mode & 0o111 != 0,
            "the installer is not executable: {mode:o}"
        );
    }

    // Defaults to the user's own data directory, so running it with no
    // arguments cannot touch a system path.
    assert!(
        text.contains(r#"prefix="${HOME}/.local""#),
        "the default prefix is not the user's own data directory"
    );
    // Nothing in it escalates.
    for forbidden in ["sudo", "pkexec", "doas", "su -"] {
        assert!(
            !text.contains(forbidden),
            "the installer reaches for {forbidden}"
        );
    }
    // Fails loudly rather than guessing, and stops on the first error: a
    // half-installed set of metadata is the state that looks like the bug it
    // is fixing.
    assert!(text.contains("set -euo pipefail"));
    assert!(text.contains("--uninstall"), "there is no way to undo it");

    // And the application does not run it. An application that installs
    // things into a home directory when it starts is doing something nobody
    // asked for, and the brief for this work forbids it explicitly.
    //
    // Checked against *code*, with comments stripped: the source is expected
    // to discuss the installer at length — that is where the reasoning about
    // the Wayland icon chain lives — and a test that could not tell an
    // explanation from a call would have to choose between being wrong and
    // making the code undocumentable.
    for source in ["src/lib.rs", "src/main.rs", "build.rs"] {
        let text = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join(source))
            .unwrap_or_default();
        let code = strip_comments(&text);
        assert!(
            !code.contains("install-desktop-metadata"),
            "{source} runs the installer"
        );
        assert!(
            !code.contains(".local/share/applications"),
            "{source} writes desktop metadata itself"
        );
        // Nothing spawns anything, which is the general form of the rule.
        for spawner in ["Command::new", "std::process::Command"] {
            assert!(
                !code.contains(spawner),
                "{source} spawns a process ({spawner})"
            );
        }
    }
}

/// Rust source with `//` line comments — doc comments included — removed.
///
/// Deliberately naive about string literals containing `//`, which would make
/// it drop the tail of such a line. That direction is safe here: it can only
/// hide a match, and every assertion using it is a *negative* one whose job is
/// to fail on code. A URL in a string would be the false negative, and there
/// is none in the three files this reads.
fn strip_comments(source: &str) -> String {
    source
        .lines()
        .map(|line| match line.find("//") {
            Some(at) => &line[..at],
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

// ===========================================================================
// KDE-SNI-01 — the D-Bus activation metadata
// ===========================================================================
//
// `DBusActivatable=true` has been in the desktop entry since the Quick Panel
// sprint and it is not, on its own, enough to start anything. It is a promise
// read by things that launch desktop entries; the message bus reads a service
// file instead, and there was none. Measured before this sprint added one:
//
//     $ gdbus call --session --dest io.github.yurisismotto.pliwee … \
//           --method org.freedesktop.Application.ActivateAction quick-panel '[]' '{}'
//     Error: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
//
// The KDE tray item needs the cold case to work, so the service file is now
// installed beside the other two. These pin the four strings that have to
// agree for it to: the bus name, the entry's basename, the binary, and the
// flag that keeps a cold start from opening a window nobody asked for.

/// The D-Bus activation template. `.in`, because one line has to be derived
/// from the install prefix.
fn dbus_service_template() -> String {
    std::fs::read_to_string(data().join(format!("{}.service.in", app_id_from_source())))
        .expect("the D-Bus service template is readable")
}

/// One key from the `[D-BUS Service]` group of the template.
fn dbus_service_key(key: &str) -> Option<String> {
    let text = dbus_service_template();
    let mut in_group = false;
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_group = line == "[D-BUS Service]";
            continue;
        }
        if !in_group || line.starts_with('#') {
            continue;
        }
        if let Some(value) = line.strip_prefix(&format!("{key}=")) {
            return Some(value.to_string());
        }
    }
    None
}

/// The bus name the service file claims is the application id, and the file
/// is named after it.
#[test]
fn the_dbus_activation_entry_claims_the_application_id() {
    let app_id = app_id_from_source();
    let template = data().join(format!("{app_id}.service.in"));
    assert!(
        template.is_file(),
        "no D-Bus activation template at {} — without one the bus cannot start \
         OmniBridge, and the tray's cold-start path does not exist",
        template.display()
    );
    assert_eq!(
        dbus_service_key("Name").as_deref(),
        Some(app_id.as_str()),
        "the service file claims a bus name that is not the application id"
    );
}

/// The `Exec` line: the same binary the desktop entry launches, in service
/// mode, from a prefix rather than from anywhere in this checkout.
#[test]
fn the_dbus_activation_entry_starts_the_gui_in_service_mode() {
    let exec = dbus_service_key("Exec").expect("the service file declares Exec");

    // `--gapplication-service` is what stops a cold activation opening a
    // window the person did not ask for: without it the bus starts the binary
    // with no arguments, which is a bare launch, which opens Settings — and
    // then the activation message arrives and opens the Quick Panel too.
    assert!(
        exec.ends_with(" --gapplication-service"),
        "Exec is {exec:?}; a cold activation would open an unasked-for window"
    );

    // Derived from the prefix, and never from a developer's home directory or
    // a repository path. `@BINDIR@` is the only variable part.
    assert!(
        exec.starts_with("@BINDIR@/"),
        "Exec is {exec:?}; a D-Bus service file's Exec must be absolute, and the \
         only honest source of an absolute path is the install prefix"
    );
    for wrong in ["/home/", "Sandbox", "target/debug", "..", "~"] {
        assert!(
            !exec.contains(wrong),
            "Exec contains {wrong:?}, which is a path from somebody's machine"
        );
    }

    // The same program the desktop entry runs.
    let desktop_exec = desktop_entry_key("Exec").expect("the desktop entry declares Exec");
    let program = |line: &str| {
        line.split_whitespace()
            .next()
            .expect("a program")
            .rsplit('/')
            .next()
            .expect("a basename")
            .to_string()
    };
    assert_eq!(
        program(&exec),
        program(&desktop_exec),
        "the bus would start a different program than the launcher does"
    );

    // And the entry still declares itself activatable, which is the half of
    // the pair that things launching desktop entries read.
    assert_eq!(
        desktop_entry_key("DBusActivatable").as_deref(),
        Some("true"),
        "the desktop entry no longer declares itself D-Bus activatable"
    );
}

/// The installer puts it where the bus looks, substitutes the prefix and not
/// the staging root, and takes it away again.
#[test]
fn the_installer_handles_the_activation_entry_like_the_other_two() {
    let app_id = app_id_from_source();
    let installer = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tools/install-desktop-metadata.sh"),
    )
    .expect("the installer is readable");

    assert!(
        installer.contains("share/dbus-1/services"),
        "the installer does not write into a D-Bus service directory"
    );
    assert!(
        installer.contains("$APP_ID.service"),
        "the installer does not name the service file after the application id"
    );
    assert!(
        installer.contains("$APP_ID.service.in") || installer.contains("DBUS_SRC="),
        "the installer does not read the template"
    );

    // The substitution takes `$prefix`, the path the file will be read at, and
    // never `$destdir`, which is a staging root that does not exist on the
    // machine that ends up reading it. Getting this backwards produces a
    // package whose service file points into a buildroot.
    assert!(
        installer.contains(r#"s|@BINDIR@|$prefix/bin|g"#),
        "the installer does not substitute @BINDIR@ from the install prefix"
    );
    assert!(
        !installer.contains("@BINDIR@|$destdir"),
        "the installer bakes the staging root into the service file"
    );

    // The bus does not watch its service directories — measured on Fedora 44,
    // whose bus is dbus-broker: the activation failed until `ReloadConfig` was
    // sent. Without this line a development install silently works only after
    // the next login.
    assert!(
        installer.contains("ReloadConfig"),
        "the installer does not tell the session bus to reread its services"
    );

    // And uninstall removes it, or an uninstalled OmniBridge leaves the bus able
    // to start a binary that is no longer there.
    let uninstall_block = installer
        .split("if [ \"$uninstall\" -eq 1 ]")
        .nth(1)
        .expect("the installer has an uninstall path");
    assert!(
        uninstall_block.contains("$dbus_dst"),
        "uninstall leaves the D-Bus activation entry behind"
    );
    let _ = app_id;
}

// ===========================================================================
// PLIWEE-W7 — the desktop artwork derives from the Pliwee masters
// ===========================================================================
//
// Wave 7 moves the desktop off the OmniBridge artwork. The brand mark is the
// frozen master itself, compiled in; the application icon is a placement of
// that master on the 512-unit grid, produced by
// `docs/reports/branding/pliwee-wave-7/derive_desktop_app_icon.py`. These
// re-prove the derivation from the files, so a hand edit to the icon, or a
// build that quietly goes back to the old artwork, fails here.

/// The block between `<defs>` and `</defs>`, inclusive.
fn defs_block(svg: &str) -> &str {
    let start = svg.find("<defs>").expect("a <defs> block");
    let end = svg.rfind("</defs>").expect("a closing </defs>") + "</defs>".len();
    &svg[start..end]
}

/// The icon is the master's artwork, copied byte for byte, drawn once.
///
/// Byte equality of the whole `<defs>` block covers the four paths, the clip,
/// every gradient stop and the `mark` symbol's own viewBox and paint order —
/// there is nothing in the icon's artwork that the master did not supply.
/// What follows the defs is one `<use>` of that symbol, square and on the
/// 512-unit grid, so the symbol's own viewBox and the default
/// `preserveAspectRatio` scale it uniformly: nothing is stretched.
#[test]
fn the_desktop_app_icon_is_a_placement_of_the_pliwee_master() {
    let master = read("pliwee-mark.svg");
    let icon = read("pliwee-app-icon.svg");

    let master_defs = defs_block(&master);
    assert!(
        master_defs.len() > 20_000,
        "the master's defs are implausibly short ({} bytes), so equality would prove little",
        master_defs.len()
    );
    assert_eq!(
        defs_block(&icon),
        master_defs,
        "pliwee-app-icon.svg's artwork is not the master's, byte for byte"
    );
    assert_eq!(attr(&icon, "viewBox").as_deref(), Some("0 0 512 512"));

    let drawn = icon
        .rsplit_once("</defs>")
        .expect("content after the defs")
        .1;
    assert_eq!(
        drawn.trim(),
        "<use href=\"#mark\" x=\"50\" y=\"50\" width=\"412\" height=\"412\"/></svg>",
        "the icon draws something other than one square placement of the mark"
    );
    assert!(
        !icon.contains("preserveAspectRatio"),
        "the mark must not be stretched"
    );

    let lower = icon.to_lowercase();
    for dead in [
        "anyflow",
        "flow a",
        "flow-a",
        "flow_a",
        "flowing",
        "fedroid",
        "omnibridge",
        "one bridge",
    ] {
        assert!(
            !lower.contains(dead),
            "pliwee-app-icon.svg carries {dead:?}"
        );
    }
}

/// The in-app mark and the compiled-in resources are the Pliwee artwork.
#[test]
fn the_desktop_compiles_in_the_pliwee_masters() {
    let gresource = std::fs::read_to_string(data().join("pliwee.gresource.xml"))
        .expect("the resource list is readable");
    for file in [
        "<file preprocess=\"xml-stripblanks\">pliwee-mark.svg</file>",
        "<file preprocess=\"xml-stripblanks\">pliwee-mark-mono.svg</file>",
        "<file preprocess=\"xml-stripblanks\">pliwee-app-icon.svg</file>",
    ] {
        assert!(
            gresource.contains(file),
            "the resource list does not carry {file}"
        );
    }
    assert!(
        gresource.contains("<gresource prefix=\"/io/github/yurisismotto/pliwee\">"),
        "the resources are not compiled under the application id's path"
    );

    let widgets =
        std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("src/widgets.rs"))
            .expect("src/widgets.rs is readable");
    assert!(
        widgets.contains("from_resource(\"/io/github/yurisismotto/pliwee/pliwee-mark.svg\")"),
        "brand_mark() does not draw the Pliwee master"
    );
    assert!(
        !widgets.contains("omnibridge-mark"),
        "the GUI still draws the OmniBridge mark"
    );
}
